name: "cargo-generate"
description: "Runs cargo-generate"

inputs:
  name:
    description: "The name of the project to generate."
    required: true
  template:
    description: "The template to use for generating the project (passed to cargo-generate using --path)."
    required: false
    default: "."
  subfolder:
    description: "The subfolder the template lives in."
    required: false
  arguments:
    description: "Additional arguments passed to cargo-generate"
    required: false
    default: "--verbose"

outputs: {}

runs:
  using: docker
  image: Dockerfile
